#!/usr/bin/env python3
"""sources/media/*.png -> deck/assets.py  (base64 data URIs)

The deck ships as ONE self-contained HTML file, so every image has to travel inside it.
This trims transparent margins, resizes to about 2x the display size, and writes each
image out as a `data:image/png;base64,...` constant.

Why regenerate rather than hand-edit: `deck/assets.py` is derived, and the rule in
CLAUDE.md is that anything derived must be reproducible by a script in tools/. The
originals in sources/media/ are the evidence and are never edited.

Nominative use only. Every logo here identifies the company being discussed, at the
point it is discussed. Nothing in the deck is styled to imply Braze produced it, and
the title slide's mark is Braze's wordmark on a plate captioned as the subject of the
analysis, not as its author.

Usage:  python3 tools/build_assets.py
"""
import base64
import io
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "sources", "media")
OUT = os.path.join(REPO, "deck", "assets.py")

# (constant, filename, target width in px, format, note for the generated file)
# Logos stay PNG because they need the alpha channel; photographs go to JPEG, which is
# roughly a fifth of the size at a quality nobody can see the difference at on a slide.
ASSETS = [
    ("LOGO", "braze-logo.png", 300, "png",
     "Braze wordmark, from the site header at braze.com. Black on transparent, so it "
     "needs a light plate behind it on this deck's dark ground."),
    ("OFFERFIT", "offerfit-logo.png", 420, "png",
     "OfferFit's own logo, from the Internet Archive capture of offerfit.ai dated "
     "2024-12-31. It is not on the live web: offerfit.ai now serves a Braze page "
     "titled 'BrazeAI Decisioning Studio' and carries Braze's logo in its header."),
    ("CEO", "ceo-magnuson.png", 260, "jpg",
     "Bill Magnuson, from Braze's own investor-relations leadership page, where the "
     "alt text reads 'Chairman, Chief Executive Officer, President, and Cofounder'."),
    ("FOUNDERS", "founders-2011-techcrunch-disrupt.png", 560, "jpg",
     "Braze's CEO and CTO at TechCrunch Disrupt NYC in 2011, published by Braze on "
     "its own /company page under 'How it started'. Deliberately NOT captioned "
     "left-to-right: the source labels the pair 'CEO and CTO' and does not say which "
     "is which, and guessing would be an identification the evidence does not carry."),
]


def trim(im):
    """Drop fully transparent margins. A logo with 40% empty pixels renders small."""
    if im.mode != "RGBA":
        return im
    bbox = im.getchannel("A").getbbox()
    return im.crop(bbox) if bbox else im


def encode(path, width, fmt):
    im = Image.open(path).convert("RGBA")
    im = trim(im)
    if im.width > width:
        h = round(im.height * width / im.width)
        im = im.resize((width, h), Image.LANCZOS)
    buf = io.BytesIO()
    if fmt == "jpg":
        # Flatten onto white: these sit on a light plate or a circular crop, so the
        # matte never shows, and JPEG has no alpha to lose.
        flat = Image.new("RGB", im.size, (255, 255, 255))
        flat.paste(im, mask=im.getchannel("A"))
        flat.save(buf, "JPEG", quality=78, optimize=True, progressive=True)
        mime = "jpeg"
    else:
        im.save(buf, "PNG", optimize=True)
        mime = "png"
    return base64.b64encode(buf.getvalue()).decode(), im.size, len(buf.getvalue()), mime


def main():
    lines = [
        "# -*- coding: utf-8 -*-",
        '"""Generated by tools/build_assets.py — do not edit by hand.',
        "",
        "Images as base64 data URIs so deck/braze-deck.html stays a single file that can be",
        "emailed, opened offline and printed without fetching anything. Originals and their",
        "provenance are in sources/media/.",
        '"""',
        "",
    ]
    total = 0
    for const, fname, width, fmt, note in ASSETS:
        path = os.path.join(SRC, fname)
        if not os.path.exists(path):
            print("MISSING %s — %s not written" % (fname, const))
            continue
        b64, size, nbytes, mime = encode(path, width, fmt)
        total += nbytes
        lines.append("# %s" % note.replace(". ", ".\n# "))
        lines.append("# %s -> %dx%d %s, %.0f KB" % (fname, size[0], size[1], mime, nbytes / 1024))
        lines.append('%s = "data:image/%s;base64,%s"' % (const, mime, b64))
        lines.append("")
        print("%-10s %-38s %4dx%-4d %6.0f KB" % (const, fname, size[0], size[1], nbytes / 1024))

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("wrote deck/assets.py — %d images, %.0f KB of PNG before base64" % (len(ASSETS), total / 1024))


if __name__ == "__main__":
    main()
